LaunchRouter now will come with UIWindow instead of UIViewController
uber/RIBs pull request #284
Opened 2018-10-12 05:31 UTC by dangthaison91

This PR related to issue #281.

**Description**:
This will replace UIViewController by UIWindow in LaunchRouter. This will help we create View Hierarchy as before: SignIn/Home/Main... will be set as UIWindow.rootViewController. They will longer be present from RootViewController.

In a short way, RootViewController now becomes a UIWindow.

2018-10-12 05:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/uber/RIBs?pullRequest=284) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/uber/RIBs?pullRequest=284) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/uber/RIBs?pullRequest=284) it.</sub>

2018-10-12 17:31 UTC, neakor commented
I'm not sure I follow why we are making this change? The original setup is to allow the creation of `UIWindow` independent of RIBs. `UIWindow` is strictly a UIKit concept that's outside the domain of RIBs. I would rather not push this logic into the router.

2018-10-12 17:32 UTC, neakor requested changes
I'm not sure I follow why we are making this change? The original setup is to allow the creation of `UIWindow` independent of RIBs. `UIWindow` is strictly a UIKit concept that's outside the domain of RIBs. I would rather not push this logic into the router.

2018-10-15 17:50 UTC, neakor commented
@dangthaison91 instead of modifying the existing one, can we add a new one?

2018-10-15 17:54 UTC, dangthaison91 commented
@neakor I'm not sure new one like `WindowRouter` or something else will make sense? Introduce new Router type could make RIB framework a little bit more complex? Could you share your ideas?

How about store UIWindow as a property inside LaunchRouter and provide a `replaceRootViewController(:)`?

2018-10-15 20:11 UTC, neakor commented
The logic of replacing the root view controller doesn't seem related to Router or RIB to me. Can we just do this logic outside of the `LaunchRouter`?

2018-10-15 22:55 UTC, ermik commented
`rootViewController` is a platform convention, it's part of how storyboards work or it is implemented by the developer themselves. If we agree RIBs have no business creating UIWindow or rootViewController, it is important to say `launchFrom` feels like a natural of other RIBs idioms. It fits.

Also, this PR doesn't touch the tutorials code and has some comments that it has missed in the code.

2018-10-22 18:43 UTC, dangthaison91 commented
> The logic of replacing the root view controller doesn't seem related to Router or RIB to me.
IMHO, we are configuring rootViewController inside LaunchRouter, which is against your statement. Should we change `LaunchRouter` to have a `UIWindow` instead of UIViewController?  Then we leave user decide how to configure their view hierarchy inside their `LaunchRouter` subclass?

Another option is introducing `WindowRouter` but I think we will have some questions about  the name and the existing of `LaunchRouter`

2018-10-23 07:48 UTC, sbarow commented
This PR doesn't make sense, please use the solution suggested in #281

2018-11-04 14:56 UTC, dangthaison91 commented
I ended up by creating WindowRouter for internal use only instead of modifying LaunchRouter. Need time to see how it works also consider other approaches.

2018-11-05 19:21 UTC, neakor commented
@dangthaison91 I'll close this PR for now. Please let us know in the future. Thanks for the contribution!

2018-11-05 19:21 UTC, closed without merging