Update Android repo to Kotlin 1.7.10
uber/RIBs pull request #528
Opened 2022-12-02 14:18 UTC by SharmaDhruv2511

**Description**:

**Related issue(s)**:

2022-12-02 14:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/uber/RIBs?pullRequest=528) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/uber/RIBs?pullRequest=528) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/uber/RIBs?pullRequest=528) it.</sub>

2022-12-02 14:23 UTC, SharmaDhruv2511 commented
It's been a great experience to change the code from Java to Kotlin. Get to learn more about how to write the code and how to review the code, 
This is my first time to contributing to Open Source and its been great experience

2022-12-08 16:37 UTC, tyvsmith commented on android/tutorials/tutorial1/src/test/java/com/uber/rib/root/RootInteractorTest.kt
>  @SuppressWarnings("NullAway")
Please remove the Nullaway suppressions, they are java specific.

2022-12-08 16:43 UTC, tyvsmith requested changes
Please don't check in the lib jars to the repo.

2022-12-08 16:43 UTC, tyvsmith commented
@SharmaDhruv2511 Thank you for the contribution, I've left some comments to address.

2022-12-11 08:59 UTC, SharmaDhruv2511 commented
I have made the changes. Please check it out

2022-12-15 06:01 UTC, SharmaDhruv2511 commented
@tyvsmith please check the code and enable the merge request!

2022-12-15 17:20 UTC, tyvsmith commented
Thanks, but it looks like my comments weren't addressed. 

1. Please adjust all of the nullable mocks to nonnull lateinit vals.
2. Please remove all the java specific annotations that are no longer needed, including all the nullaway ones, unchecked, etc.

The rest looks reasonable to mege.

2022-12-18 14:47 UTC, SharmaDhruv2511 commented
> Thanks, but it looks like my comments weren't fully addressed.
> 
> 1. Please adjust all of the nullable mocks to nonnull lateinit vals.
> 2. Please remove all the java specific annotations that are no longer needed, including all the nullaway ones, unchecked, etc.
> 
> The rest looks reasonable to merge.

2022-12-18 14:57 UTC, SharmaDhruv2511 commented
I have updated the changes please check it out @tyvsmith

2022-12-18 19:53 UTC, tyvsmith reviewed
Thanks. As mentioned before, please don't check in kotlin binary files. Additionally, my feedback still wasn't actioned for the test variables.
I also see some code that makes me think this won't compile, please verify this actually builds.

2022-12-18 19:53 UTC, tyvsmith commented on android/tutorials/tutorial4/src/main/java/com/uber/rib/RootActivity.kt
> +                .as(autoDisposable(this))(
This won't compile, has this been validated? Autodispose should use the function extension, not "as".

2022-12-18 19:53 UTC, tyvsmith commented on android/tutorials/tutorial1/src/test/java/com/uber/rib/root/RootInteractorTest.kt
> +    lateinit var presenter: RootInteractor.RootPresenter? = null
As mentioned in pervious comments, all nullable vars need to be converted to lateinit nonnull val.

2022-12-22 05:16 UTC, SharmaDhruv2511 commented
@tyvsmith check it out the code, I  hope this time it's okay

2022-12-22 19:10 UTC, tyvsmith commented
Is there a reason all the vals you changed are still nullable? All of these should explicitly be made nonnull.
I've given the feedback 3 times to change them to non null.

2022-12-27 15:16 UTC, SharmaDhruv2511 commented
> Is there a reason all the vals you changed are still nullable? All of these should explicitly be made nonnull. I've given the feedback 3 times to change them to non null.

can you help me how I should make it Non Null explicitly I read resources and all but I didn't find anything about lateinit val as a non null explicitly. Please help me out with it... @tyvsmith

2022-12-28 15:27 UTC, SharmaDhruv2511 commented
@tyvsmith ???

2023-01-04 15:55 UTC, SharmaDhruv2511 commented
I used relational operator now is it good to merge???? Please Review and reply
@tyvsmith

2023-01-04 19:41 UTC, tyvsmith commented
No,
When you're using lateinit, you don't necessarily need to make a variable nullable "?" because it's telling the compiler you'll assign in later.

So the typical pattern with testing is to make your mocked vars nonnull and set them via lateinit.

So problematic code like:
```
 @Mock lateinit val component: RootBuilder.Component?

@Before
fun setup() {
  MockitoAnnotations.initMocks(this)
}
```

Would be come something like:

```
 @Mock lateinit val component: RootBuilder.Component

@Before
fun setup() {
  MockitoAnnotations.initMocks(this)
}
```


And if that doesn't work, then change it to a nonnull var:

```
 @Mock lateinit var component: RootBuilder.Component

@Before
fun setup() {
  MockitoAnnotations.initMocks(this)
}
```

Neither have a nullable field.

Then if CI passes and this builds, it's fine to merge.

2023-01-05 16:25 UTC, SharmaDhruv2511 commented
As per your Guidance I have make all nullable mocks to Non-Null Late init val.... Please check and review 
@tyvsmith

2023-01-07 14:57 UTC, SharmaDhruv2511 commented
@tyvsmith  Can you help me with this spot check error. why it is showing???

2023-01-10 11:24 UTC, SharmaDhruv2511 commented
Waiting for approval!!! and Changes that are requested are changes

2023-01-11 09:05 UTC, SharmaDhruv2511 commented
@tyvsmith waiting for approval.....

2023-01-15 17:10 UTC, SharmaDhruv2511 commented
Merge request?? @tyvsmith

2023-01-19 17:37 UTC, tyvsmith commented
Hey @SharmaDhruv2511, as mentioned before, I ask that you don't ping maintainers directly. It is considered quite poor etiquette in the open-source community in general.

We expect our contributors to be able to solve the technical problems with their own PRs, and don't have the time to walk folks through basics on their own PRs. At this point, we will happily merge this PR once CI passes, but cannot diagnose and help with all your standard CI failures. You'll need to get this PR into a good place on your own before we'll merge.

2023-01-21 06:58 UTC, SharmaDhruv2511 commented
I have made the changes so Please approve the Changes Requested option

2023-01-30 22:54 UTC, tyvsmith requested changes
Please remove the checked-in jars and workflows changes.

2023-01-30 22:54 UTC, tyvsmith commented on .github/workflows/android.yml
> -        run: ./gradlew spotlessCheck --stacktrace
Please don't make any changes to the workflows.

2023-01-30 23:00 UTC, tyvsmith commented
Please ensure local builds pass fully with `./gradlew spotlessCheck assemble test check` to expect CI to pass once the PR is up.

2023-01-31 14:11 UTC, digitalbuddha commented
Hello  @SharmaDhruv2511 

Reviewers will not start review again until all of the GitHub actions pass. Similar it I'd make sure you address ALL comments prior to getting a review.

Since this is a large change review can take upwards of weeks. 

Similar there is no guarantee that the code will be accepted. This is a very popular project that needs to take care when making a significant change this size. 

My recommendation would be to read through every comment Ty made. Make sure you apply each suggestion. 

If anything does not make sense you can post a comment here but this is not a good medium for learning how something should work. Stack overflow is your best bet there or official documentation for kotlin.

As mentioned above,  do not tag any reviewer directly as they already get alerts for in progress issues.

Finally, realize everyone reviewing your code is a volunteer and doing it for free. Please be civil. It comes off rude to use explanation points or to ping someone on Christmas. 

At the end of the day we are all humans trying our best to get by

2023-02-07 10:44 UTC, SharmaDhruv2511 commented
I am facing this Spot Check Error and don't know how to clear it.  Can you please help me with it?

2023-02-07 12:19 UTC, digitalbuddha commented
spotlessJava
[90](https://github.com/uber/RIBs/actions/runs/4055017569/jobs/6989063457#step:7:91)
> Task :tutorials:spotlessJavaCheck
[91](https://github.com/uber/RIBs/actions/runs/4055017569/jobs/6989063457#step:7:92)
Step 'ktlint' found problem in 'tutorials/tutorial4/src/main/java/com/uber/rib/RootActivity.kt':
[92](https://github.com/uber/RIBs/actions/runs/4055017569/jobs/6989063457#step:7:93)

[93](https://github.com/uber/RIBs/actions/runs/4055017569/jobs/6989063457#step:7:94)
44:35 Unexpected tokens (use ';' to separate expressions on the same line)

2023-04-03 06:27 UTC, closed without merging